apiVersion: v1
kind: Service
metadata:
  name: roi-calculator-client-side
  labels:
    environment: production
    tier: client
spec:
  selector:
    environment: production
    tier: client
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30011
