apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: roi-calculator
  labels:
    environment: production
    tier: client
spec:
  selector:
    app: nginx-exporter
  type: NodePort
  ports:
    - port: 9113
      targetPort: 9113
      nodePort: 30913